// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TrainTicketSales.Models.Entity
{
    public partial class Cabin
    {
        public Cabin()
        {
            Seat = new HashSet<Seat>();
        }

        public long Id { get; set; }
        public string CabinCategoryCode { get; set; }
        public string Index { get; set; }
        public string TrainCode { get; set; }

        public virtual CabinCategory CabinCategoryCodeNavigation { get; set; }
        public virtual Train TrainCodeNavigation { get; set; }
        public virtual ICollection<Seat> Seat { get; set; }
    }
}