// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TrainTicketSales.Models.Entity
{
    public partial class SaleOrder
    {
        public SaleOrder()
        {
            SaleOrderDetail = new HashSet<SaleOrderDetail>();
        }

        public long Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public DateTime? OrderDate { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string IdentityCard { get; set; }
        /// <summary>
        /// 1: đặt mua; 2: chấp nhận bán; 3: trả tiền; 4: xác nhận nhận tiền, 5:  giao vé, 6: hoãn, 7: đổi chuyển
        /// </summary>
        public int? Status { get; set; }

        public virtual ICollection<SaleOrderDetail> SaleOrderDetail { get; set; }
    }
}