// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TrainTicketSales.Models.Entity
{
    public partial class SaleOrderDetail
    {
        public long Id { get; set; }
        public long? SaleOrderId { get; set; }
        public string Name { get; set; }
        public string IdentityCard { get; set; }
        public bool? Adult { get; set; }
        public long? SeatDetailId { get; set; }

        public virtual SaleOrder SaleOrder { get; set; }
        public virtual SeatDetail SeatDetail { get; set; }
    }
}