// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TrainTicketSales.Models.Entity
{
    public partial class Schedule
    {
        public Schedule()
        {
            SeatDetail = new HashSet<SeatDetail>();
        }

        public long Id { get; set; }
        public long? BeginStationId { get; set; }
        public long? EndStationId { get; set; }
        public string TrainCode { get; set; }
        public DateTime? DateBegin { get; set; }
        public DateTime? DateEnd { get; set; }

        public virtual Station BeginStation { get; set; }
        public virtual Station EndStation { get; set; }
        public virtual Train TrainCodeNavigation { get; set; }
        public virtual ICollection<SeatDetail> SeatDetail { get; set; }
    }
}