// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TrainTicketSales.Models.Entity
{
    public partial class Seat
    {
        public long Id { get; set; }
        public string CabinCode { get; set; }
        public string SeatCode { get; set; }
        public string TrainId { get; set; }
    }
}