// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TrainTicketSales.Models.Entity
{
    public partial class SeatDetail
    {
        public long ScheduleId { get; set; }
        public long SeatId { get; set; }
        public long? Price { get; set; }
        public bool? Status { get; set; }

        public virtual Schedule Schedule { get; set; }
        public virtual Seat Seat { get; set; }
    }
}