// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TrainTicketSales.Models.Entity
{
    public partial class Station
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Km { get; set; }
        public string Address { get; set; }
        public int? Index { get; set; }
    }
}